require("globals")

require("better_window_line_numbers")
require("color_scheme")
require("find_file")
require("floating_terminal")
require("hex")
require("keymaps")
require("lsp")
require("options")
require("status_line")
require("plugins.init")
